# Generated by Django 4.0.3 on 2022-03-10 12:19

from django.db import migrations
import os


def create_superuser(apps, schema_editor):
    username = os.getenv('DJANGO_SU_NAME')
    email = os.getenv('DJANGO_SU_EMAIL')
    password = os.getenv('DJANGO_SU_PASSWORD')

    User = apps.get_model('accounts', 'CustomUser')

    User.objects.create_superuser(username=username,
                                  email=email,
                                  password=password)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
